version: '2'

services:

  bibbox-seeddms:
    image: quay.io/mivegec/seeddms:dev
    build:
      context: images/seeddms
    container_name:  bibbox-seeddms
    restart: always  
    links:
      - bibbox-seeddms-db:seeddms-db
    ports:
      - "8065:80"
    depends_on:
      - bibbox-seeddms-db
    volumes: 
      - "./data/seeddms:/var/www/seeddms51x/data:rw"
      - "./conf/settings.xml:/var/www/seeddms51x/conf/settings.xml:rw"
      
  bibbox-seeddms-db:
    image: mariadb:10.3
    container_name: bibbox-seeddms-db
    environment:
      - MYSQL_ROOT_PASSWORD=bibbox
      - MYSQL_DATABASE=seeddms
      - MYSQL_USER=seeddms
      - MYSQL_PASSWORD=seeddms4bibbox
    volumes:
      - "./data/mysql:/var/lib/mysql:rw"

