version: '2'

services:

  bibbox-ldap:
    image: rroemhild/test-openldap
    restart: always  
#    ports:
#      - "389:389"
        
  bibbox-seeddms:
    image: quay.io/mivegec/seeddms:dev
    build:
      context: images/seeddms
    container_name:  dev-bibbox-seeddms
    restart: always  
    links:
      - bibbox-seeddms-db:seeddms-db
    ports:
      - "8066:80"
    depends_on:
      - bibbox-seeddms-db
    volumes: 
      - "./data/seeddms:/var/www/seeddms51x/data:rw"
      - "./conf/:/var/www/seeddms51x/conf/:rw"
      - "./phpinfo.php:/var/www/seeddms51x/seeddms/phpinfo.php:rw"
      
  bibbox-seeddms-db:
    image: mariadb:10.3
    container_name: dev-bibbox-seeddms-db
    environment:
      - MYSQL_ROOT_PASSWORD=bibbox
      - MYSQL_DATABASE=seeddms
      - MYSQL_USER=seeddms
      - MYSQL_PASSWORD=seeddms4bibbox
    volumes:
      - "./data/mysql:/var/lib/mysql:rw"

